version: "3.0"

services:
  service:
    image: namespace-service:latest
    restart: always
    depends_on:
      - db
    ports:
      - 4003:4003
    expose:
      - "4003"
    build: ./
    environment:
      DOCKER_DB_URL: postgresql://user:password@db:5432/namespace-db
    command: npm start


  db:
    image: postgres:13.7-bullseye
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: namespace-db
    volumes:
      - db-data:/db-data/

volumes:
  db-data:
